# Generated by Django 4.0.3 on 2022-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_faction_alter_character_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('human', 'human'), ('dwarf', 'dwarf'), ('night elf', 'night elf'), ('gnome', 'gnome'), ('worgen', 'worgen'), ('void Elf', 'void elf'), ('lightforged draenei', 'lightforged draenei'), ('dark iron dwarf', 'dark iron dwarf'), ('kultiran', 'kultiran'), ('mechagnome', 'mechagnome'), ('orc', 'orc'), ('undead', 'undead'), ('tauren', 'tauren'), ('troll', 'troll'), ('blood elf', 'blood elf'), ('goblin', 'goblin'), ('nightborne', 'nightborne'), ('highmountain tauren', 'highmountain tauren'), ('maghar orc', 'maghar orc'), ('zandalari troll', 'zandalari troll'), ('vulpera', 'vulpera'), ('pandaren', 'pandaren')], max_length=21),
        ),
    ]
